export const styles = {
    main: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: "1rem 2rem",
    },
    mainHeading: {
        fontSize: "1.5rem",
        fontWeight: "500",
        color: "#000000",
    },
    mainData: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: "2rem",
    },
    mainDataLeft: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        width: "50%",
    },
    mainDataLeftLeft: {
        display: "flex",
        marginBottom: "0.5rem",
    },
    mainDataLeftLeftLeft: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
    },
    mainDataLeftLeftRight: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
    },
    bankText: {
        fontSize: "0.9rem",
        fontWeight: "400",
        lineHeight: "1.5",
    },
    mainDataRight: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "50%",
        paddingLeft: "7rem",
    },
    mainDataNewRight: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        paddingLeft: "30rem",
    },
    mainDataRightLeft: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        gap: "0.1rem",
        width: "50%",
    },
    mainDataRightRight: {
        gap: "0.1rem",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        width: "50%",
    },
    statsText: {
        fontSize: "1rem",
        fontWeight: "400",
        lineHeight: "1.5",
        color: "#000000",
    },
    statsTextValue: {
        fontSize: "1rem",
        fontWeight: "400",
        lineHeight: "1.5",
        display: "flex",
        justifyContent: "space-between",
    },
    statsCurrency: {
        fontWeight: "500",
        marginRight: "0.3rem",
    },
    sectionHeader: {
        fontSize: 12,
        fontWeight: "bold",
        marginTop: 10,
        marginBottom: 5,
        width: "100%",
        borderBottomWidth: 1,
        borderBottomColor: "#e0e0e0",
        paddingBottom: 3,
    },
};

export const pdfStyle = {
    main: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: "10px 40px",
        // height: "120px",
    },
    mainHeading: {
        fontSize: "12px",
        fontWeight: "normal",
        color: "#000000",
        marginBottom: "5px",
    },
    mainData: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        gap: "40px",
    },
    mainDataLeft: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        width: "55%",
    },
    mainDataLeftLeft: {
        display: "flex",
        flexDirection: "row",
    },
    mainDataLeftLeftLeft: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
    },
    mainDataLeftLeftRight: {
        width: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
    },
    bankText: {
        fontSize: "8px",
        fontWeight: "normal",
        lineHeight: "1.5",
    },
    mainDataRight: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "50%",
        paddingLeft: "50.4px",
    },
    mainDataNewRight: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        paddingLeft: "337px",
    },
    mainDataRightLeft: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "flex-start",
        gap: "1px",
        width: "50%",
    },
    mainDataRightRight: {
        gap: "1px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        width: "50%",
    },
    statsText: {
        fontSize: "8px",
        fontWeight: "normal",
        lineHeight: "1.5",
        color: "#000000",
    },
    statsTextValue: {
        fontSize: "8px",
        fontWeight: "400",
        lineHeight: "1.5",
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    statsCurrency: {
        fontWeight: "bold",
        marginRight: "16px",
        fontSize: "8px",
    },
    sectionHeader: {
        fontSize: 12,
        fontWeight: "bold",
        width: "100%",
        borderBottomWidth: 1,
        borderBottomColor: "#e0e0e0",
        paddingBottom: 3,
    },
};
